#! /usr/bin/env python

# imports of external packages to use in our code
import sys
import numpy as np
import matplotlib.pyplot as plt

# main function for this Python code
if __name__ == "__main__":
       
    my_file = open("testfile.txt", "r")
    content = my_file.read()
    #print(content)
    
    # convert content to array for histogram
    content_array = eval('[' + content + ']')
    print(content_array)
    
    # create histogram of our data
    n, bins, patches = plt.hist(content_array, bins=50, density=True, facecolor='gray', alpha=0.75)

    # plot formating options
    plt.xlabel('x')
    plt.ylabel('Probability')
    plt.title('Uniform random number')
    plt.grid(True)

    # show figure (program only ends once closed
    plt.show()
